Topic:
->One hot encoding
->Bag of words
->tf-idf

In [3]:
import pandas as pd

In [4]:
data=pd.DataFrame({"text":["people watch ineuron",'ineuron watch ineuron','people write comment','ineuron write comment'],"output":[1,1,0,0]})

In [5]:
data

text  output
0   people watch ineuron       1
1  ineuron watch ineuron       1
2   people write comment       0
3  ineuron write comment       0

In [6]:
#Document matrix(BOW)

In [7]:
from sklearn.feature_extraction.text import CountVectorizer

In [8]:
BOW=CountVectorizer()

In [9]:
document_matrix=BOW.fit_transform(data["text"])

In [10]:
document_matrix

<4x5 sparse matrix of type '<class 'numpy.int64'>'
	with 11 stored elements in Compressed Sparse Row format>

In [11]:
BOW.vocabulary_

{'people': 2, 'watch': 3, 'ineuron': 1, 'write': 4, 'comment': 0}

In [12]:
document_matrix[0].toarray()

array([[0, 1, 1, 1, 0]])

In [13]:
document_matrix[1].toarray()

array([[0, 2, 0, 1, 0]])

In [14]:
document_matrix[2].toarray()

array([[1, 0, 1, 0, 1]])

In [15]:
document_matrix[3].toarray()

array([[1, 1, 0, 0, 1]])

In [28]:
bigram=CountVectorizer(ngram_range=(2,2))

In [29]:
bigramvocab=bigram.fit_transform(data["text"])

In [30]:
bigram.vocabulary_

{'people watch': 2,
 'watch ineuron': 4,
 'ineuron watch': 0,
 'people write': 3,
 'write comment': 5,
 'ineuron write': 1}

In [32]:
trigram=CountVectorizer(ngram_range=(3,3))

In [33]:
trigramvocab=trigram.fit_transform(data['text'])

In [35]:
trigram.vocabulary_

{'people watch ineuron': 2,
 'ineuron watch ineuron': 0,
 'people write comment': 3,
 'ineuron write comment': 1}

In [36]:
mix=CountVectorizer(ngram_range=(1,2))

In [38]:
mix_vocab=mix.fit_transform(data['text'])

In [39]:
mix.vocabulary_

{'people': 4,
 'watch': 7,
 'ineuron': 1,
 'people watch': 5,
 'watch ineuron': 8,
 'ineuron watch': 2,
 'write': 9,
 'comment': 0,
 'people write': 6,
 'write comment': 10,
 'ineuron write': 3}

In [41]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [42]:
tfidf=TfidfVectorizer()

In [44]:
tfidf.fit_transform(data['text']).toarray()

array([[0.        , 0.49681612, 0.61366674, 0.61366674, 0.        ],
       [0.        , 0.8508161 , 0.        , 0.52546357, 0.        ],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.57735027],
       [0.61366674, 0.49681612, 0.        , 0.        , 0.61366674]])

In [45]:
tfidf.get_feature_names_out()

array(['comment', 'ineuron', 'people', 'watch', 'write'], dtype=object)

In [46]:
tfidf.idf_

array([1.51082562, 1.22314355, 1.51082562, 1.51082562, 1.51082562])