In [1]:
# What is feature extraction from text/images
# Why we need it
# Why it is so difficult
# What is the core idea
# Some techniques

# One hot encoding

In [2]:
# drawbacks of one hot encoding
# sparsity
# no fixed size
# out of vocabulary issues
# not capturing semantics meaning

# Bag of Words

* D1 people watch dswithbappy
* D2 dswithbappy watch dswithbappy
* D3 people write comments
* D4 dswithbappy write comments

* Unique Words/Documents   people watch dswithbappy write comments
* D1                         1      1     1           0     0
* D2                         0      1      2          0     0
* D3                         1       0     0           1    1
* D4                         0       0     1           1     1

In [3]:
# Drawbacks

# Not capturing the semantics meaning

# Tf-idf

# Word2Vec

# Bag of Words

In [4]:
import pandas as pd
import numpy as np

In [5]:
df=pd.DataFrame({"text":["people watch dswithbappy",
                         "dswithbappy watch dswithbappy",
                         "people write comments",
                         "dswithbappy write comments"],"outputs":[1,1,0,0]})

In [6]:
df

text  outputs
0       people watch dswithbappy        1
1  dswithbappy watch dswithbappy        1
2          people write comments        0
3     dswithbappy write comments        0

In [7]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()

In [8]:
bag_of_words=cv.fit_transform(df['text'])

In [9]:
bag_of_words

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 11 stored elements and shape (4, 5)>

In [10]:
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'dswithbappy': 1, 'write': 4, 'comments': 0}


In [11]:
bag_of_words.toarray()

array([[0, 1, 1, 1, 0],
       [0, 2, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [1, 1, 0, 0, 1]])

In [12]:
bag_of_words[1].toarray()     # Document2

array([[0, 2, 0, 1, 0]])

In [13]:
X=bag_of_words.toarray()
y=df['outputs']

# N-grams

In [14]:
df=pd.DataFrame({"text":["people watch dswithbappy",
                         "dswithbappy watch dswithbappy",
                         "people write comments",
                         "dswithbappy write comments"],"outputs":[1,1,0,0]})

In [15]:
# bi-grams
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(ngram_range=(2,2))


In [16]:
bow=cv.fit_transform(df['text'])

In [17]:
print(cv.vocabulary_)

{'people watch': 2, 'watch dswithbappy': 4, 'dswithbappy watch': 0, 'people write': 3, 'write comments': 5, 'dswithbappy write': 1}


In [18]:
bow.toarray()

array([[0, 0, 1, 0, 1, 0],
       [1, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 1],
       [0, 1, 0, 0, 0, 1]])

# Tf-idf

In [19]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()


In [20]:
arr=tfidf.fit_transform(df['text']).toarray()

In [21]:
arr

array([[0.        , 0.49681612, 0.61366674, 0.61366674, 0.        ],
       [0.        , 0.8508161 , 0.        , 0.52546357, 0.        ],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.57735027],
       [0.61366674, 0.49681612, 0.        , 0.        , 0.61366674]])

# Word2Vec
 1. CBOW
 2. Skip-gram
     

In [22]:
import pandas as pd
import numpy as np
import gensim
import os

In [23]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /usr/share/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [24]:
df=pd.read_table('/kaggle/input/games-of-thrones/001ssb.txt')

In [25]:
df

A Game Of Thrones 
0                    Book One of A Song of Ice and Fire 
1                                By George R. R. Martin 
2                                              PROLOGUE 
3      We should start back, Gared urged as the woods...
4                                                dead." 
...                                                  ...
19001  As Daenerys Targaryen rose to her feet, her bl...
19002  nostrils. The other two pulled away from her b...
19003  unfolding and stirring the air, and for the fi...
19004                                 music of dragons. 
19005                                           Page 571

[19006 rows x 1 columns]